name: 'Setup Apple'
description: 'Setup Xcode and tools for maccatalyst and ios development'
inputs:
  verbose:  # id of input
    description: 'Verbose console output'
    required: false
    default: false
outputs:
  sdkpath: # id of output
    description: 'Path to the MacOSX SDK'
runs:
  using: 'node20'
  main: 'index.js'
