on:
  push:
    branches: [ "main" ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:

  build:
    name: "Apple Connect API"
    runs-on: macos-latest
    # always remember that macos is bash, and slash is /

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup AppleDev.Tools
      id: info
      uses: Reality-Check-Inc/setup-apple-action@v0.4
      with:
        verbose: true
