on:
  push:
    tags:
      - '*'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:

  build:
    name: "Apple Connect API"
    runs-on: macos-latest
    # always remember that macos is bash, and slash is /

    env:
      APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Tools
    - name: Setup AppleDev.Tools
      id: info
      uses: Reality-Check-Inc/setup-apple-action@v0.17
      with:
        verbose: true
        certificate: $CERTIFICATE_PATH
        certificate-passphrase: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        app-store-connect-issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        app-store-connect-key-id: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
        app-store-connect-private-key: $APP_STORE_CONNECT_PRIVATE_KEY_PATH
        bundle-identifiers: 'com.companyname.mauiapp'
        profile-types: 'IOS_APP_STORE'
